processed 8 tasks

task 1 'run-graphql'. lines 8-90:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "nPziN1DZGukFSvJ1e1AP5kJWCfjYgSTriRXB2i6BSZm",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "location": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objectConnection": {
              "nodes": [
                {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "address"
                        },
                        {
                          "name": "ascii"
                        },
                        {
                          "name": "bcs"
                        },
                        {
                          "name": "bit_vector"
                        },
                        {
                          "name": "debug"
                        },
                        {
                          "name": "fixed_point32"
                        },
                        {
                          "name": "hash"
                        },
                        {
                          "name": "option"
                        },
                        {
                          "name": "string"
                        },
                        {
                          "name": "type_name"
                        },
                        {
                          "name": "vector"
                        }
                      ]
                    }
                  }
                },
                {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "address"
                        },
                        {
                          "name": "authenticator_state"
                        },
                        {
                          "name": "bag"
                        },
                        {
                          "name": "balance"
                        },
                        {
                          "name": "bcs"
                        },
                        {
                          "name": "bls12381"
                        },
                        {
                          "name": "borrow"
                        },
                        {
                          "name": "clock"
                        },
                        {
                          "name": "coin"
                        },
                        {
                          "name": "display"
                        },
                        {
                          "name": "dynamic_field"
                        },
                        {
                          "name": "dynamic_object_field"
                        },
                        {
                          "name": "ecdsa_k1"
                        },
                        {
                          "name": "ecdsa_r1"
                        },
                        {
                          "name": "ecvrf"
                        },
                        {
                          "name": "ed25519"
                        },
                        {
                          "name": "event"
                        },
                        {
                          "name": "groth16"
                        },
                        {
                          "name": "hash"
                        },
                        {
                          "name": "hex"
                        }
                      ]
                    }
                  }
                },
                {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "genesis"
                        },
                        {
                          "name": "stake_subsidy"
                        },
                        {
                          "name": "staking_pool"
                        },
                        {
                          "name": "storage_fund"
                        },
                        {
                          "name": "sui_system"
                        },
                        {
                          "name": "sui_system_state_inner"
                        },
                        {
                          "name": "validator"
                        },
                        {
                          "name": "validator_cap"
                        },
                        {
                          "name": "validator_set"
                        },
                        {
                          "name": "validator_wrapper"
                        },
                        {
                          "name": "voting_power"
                        }
                      ]
                    }
                  }
                },
                {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::sui_system::SuiSystemState"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                        "version": "1"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                        "timestamp_ms": "0"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorState"
                      },
                      "json": {
                        "id": "0x0000000000000000000000000000000000000000000000000000000000000007",
                        "version": "1"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "asMoveObject": null,
                  "asMovePackage": {
                    "moduleConnection": {
                      "nodes": [
                        {
                          "name": "clob"
                        },
                        {
                          "name": "clob_v2"
                        },
                        {
                          "name": "critbit"
                        },
                        {
                          "name": "custodian"
                        },
                        {
                          "name": "custodian_v2"
                        },
                        {
                          "name": "math"
                        },
                        {
                          "name": "order_query"
                        }
                      ]
                    }
                  }
                },
                {
                  "location": "0x14498a4368db5cefb6ec2fe91cf18636c5d8fc08b91e3d1417ccb0866e8b95d4",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x14498a4368db5cefb6ec2fe91cf18636c5d8fc08b91e3d1417ccb0866e8b95d4",
                        "decimals": 9,
                        "name": "Sui",
                        "symbol": "SUI",
                        "description": "",
                        "icon_url": null
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0x168e8bf1317ef81399ea9fabee9e217067a257731903b45ca4915c8d049b3940",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x168e8bf1317ef81399ea9fabee9e217067a257731903b45ca4915c8d049b3940",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0x1ca7fcc2fe39d93fd041dbcbcc30b33a366b44cab26acd52e5d99f6cf2a0a6e7",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedSui"
                      },
                      "json": {
                        "id": "0x1ca7fcc2fe39d93fd041dbcbcc30b33a366b44cab26acd52e5d99f6cf2a0a6e7",
                        "pool_id": {
                          "bytes": "0xce5f1a76fad5d0b4cf8b224330e1eca393c14b7b8bc5afb2aee297e878727d5d"
                        },
                        "stake_activation_epoch": "0",
                        "principal": {
                          "value": "20000000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0x3fa556a7dadc08367a52a6eb4a3b602abbc21446c1f703d2ac46866a403d718e",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                      },
                      "json": {
                        "id": "0x3fa556a7dadc08367a52a6eb4a3b602abbc21446c1f703d2ac46866a403d718e",
                        "name": "0",
                        "value": {
                          "sui_amount": "0",
                          "pool_token_amount": "0"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0x41a7f84bd3a02e7e5bea80580e40cec419d40ef9925a51cf0128ad84b40f8041",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                      },
                      "json": {
                        "id": "0x41a7f84bd3a02e7e5bea80580e40cec419d40ef9925a51cf0128ad84b40f8041",
                        "name": {
                          "bytes": "0xce5f1a76fad5d0b4cf8b224330e1eca393c14b7b8bc5afb2aee297e878727d5d"
                        },
                        "value": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0x46ea41cad4b69f493f5cf7fcb41c96e63ea97c206107d9b25d29a7d28f683ca7",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                      },
                      "json": {
                        "id": "0x46ea41cad4b69f493f5cf7fcb41c96e63ea97c206107d9b25d29a7d28f683ca7",
                        "authorizer_validator_address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::sui_system_state_inner::SuiSystemStateInner>"
                      },
                      "json": {
                        "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                        "name": "1",
                        "value": {
                          "epoch": "0",
                          "protocol_version": "32",
                          "system_state_version": "1",
                          "validators": {
                            "total_stake": "20000000000000000",
                            "active_validators": [
                              {
                                "metadata": {
                                  "sui_address": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244",
                                  "protocol_pubkey_bytes": [
                                    181,
                                    204,
                                    219,
                                    247,
                                    152,
                                    28,
                                    246,
                                    166,
                                    166,
                                    55,
                                    97,
                                    206,
                                    205,
                                    200,
                                    164,
                                    209,
                                    239,
                                    197,
                                    175,
                                    237,
                                    254,
                                    42,
                                    204,
                                    57,
                                    23,
                                    77,
                                    4,
                                    13,
                                    248,
                                    229,
                                    243,
                                    165,
                                    113,
                                    150,
                                    21,
                                    63,
                                    67,
                                    83,
                                    57,
                                    18,
                                    166,
                                    137,
                                    44,
                                    248,
                                    183,
                                    244,
                                    122,
                                    36,
                                    4,
                                    77,
                                    194,
                                    217,
                                    26,
                                    5,
                                    133,
                                    238,
                                    76,
                                    132,
                                    112,
                                    77,
                                    62,
                                    149,
                                    117,
                                    58,
                                    29,
                                    178,
                                    172,
                                    249,
                                    17,
                                    179,
                                    207,
                                    213,
                                    199,
                                    243,
                                    162,
                                    152,
                                    239,
                                    166,
                                    169,
                                    17,
                                    254,
                                    52,
                                    86,
                                    24,
                                    220,
                                    6,
                                    57,
                                    176,
                                    195,
                                    246,
                                    167,
                                    168,
                                    199,
                                    37,
                                    41,
                                    240
                                  ],
                                  "network_pubkey_bytes": [
                                    222,
                                    193,
                                    56,
                                    253,
                                    223,
                                    140,
                                    108,
                                    228,
                                    161,
                                    246,
                                    151,
                                    172,
                                    42,
                                    190,
                                    219,
                                    243,
                                    212,
                                    210,
                                    59,
                                    152,
                                    5,
                                    6,
                                    236,
                                    134,
                                    82,
                                    53,
                                    90,
                                    224,
                                    105,
                                    93,
                                    152,
                                    85
                                  ],
                                  "worker_pubkey_bytes": [
                                    172,
                                    116,
                                    152,
                                    220,
                                    228,
                                    127,
                                    173,
                                    148,
                                    84,
                                    44,
                                    112,
                                    162,
                                    74,
                                    125,
                                    50,
                                    95,
                                    124,
                                    147,
                                    55,
                                    36,
                                    241,
                                    143,
                                    223,
                                    60,
                                    129,
                                    224,
                                    221,
                                    102,
                                    15,
                                    35,
                                    217,
                                    101
                                  ],
                                  "proof_of_possession": [
                                    128,
                                    107,
                                    74,
                                    121,
                                    76,
                                    94,
                                    1,
                                    108,
                                    22,
                                    203,
                                    69,
                                    136,
                                    24,
                                    193,
                                    194,
                                    47,
                                    140,
                                    0,
                                    140,
                                    222,
                                    97,
                                    14,
                                    177,
                                    180,
                                    60,
                                    215,
                                    201,
                                    205,
                                    116,
                                    217,
                                    249,
                                    252,
                                    64,
                                    249,
                                    177,
                                    121,
                                    185,
                                    95,
                                    201,
                                    175,
                                    255,
                                    44,
                                    236,
                                    83,
                                    92,
                                    26,
                                    136,
                                    38
                                  ],
                                  "name": "validator-0",
                                  "description": "",
                                  "image_url": {
                                    "url": ""
                                  },
                                  "project_url": {
                                    "url": ""
                                  },
                                  "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                  "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                  "primary_address": "/ip4/127.0.0.1/udp/8004/http",
                                  "worker_address": "/ip4/127.0.0.1/udp/8005/http",
                                  "next_epoch_protocol_pubkey_bytes": null,
                                  "next_epoch_proof_of_possession": null,
                                  "next_epoch_network_pubkey_bytes": null,
                                  "next_epoch_worker_pubkey_bytes": null,
                                  "next_epoch_net_address": null,
                                  "next_epoch_p2p_address": null,
                                  "next_epoch_primary_address": null,
                                  "next_epoch_worker_address": null,
                                  "extra_fields": {
                                    "id": "0xe9de3dd3274070a9883afc24174f96048c6e0dd81164ba9d42d8bb32d82860f3",
                                    "size": "0"
                                  }
                                },
                                "voting_power": "10000",
                                "operation_cap_id": {
                                  "bytes": "0x46ea41cad4b69f493f5cf7fcb41c96e63ea97c206107d9b25d29a7d28f683ca7"
                                },
                                "gas_price": "1000",
                                "staking_pool": {
                                  "id": "0xce5f1a76fad5d0b4cf8b224330e1eca393c14b7b8bc5afb2aee297e878727d5d",
                                  "activation_epoch": "0",
                                  "deactivation_epoch": null,
                                  "sui_balance": "20000000000000000",
                                  "rewards_pool": {
                                    "value": "0"
                                  },
                                  "pool_token_balance": "20000000000000000",
                                  "exchange_rates": {
                                    "id": "0xe37282ea8c4d7d88f7a7a1274a42af674d20e649909286201c10e92d5b2cdf52",
                                    "size": "1"
                                  },
                                  "pending_stake": "0",
                                  "pending_total_sui_withdraw": "0",
                                  "pending_pool_token_withdraw": "0",
                                  "extra_fields": {
                                    "id": "0xc9b7513400beb365c27ec54de13af9a04e91b39465bbca1fc9c80ce24e90d44b",
                                    "size": "0"
                                  }
                                },
                                "commission_rate": "200",
                                "next_epoch_stake": "20000000000000000",
                                "next_epoch_gas_price": "1000",
                                "next_epoch_commission_rate": "200",
                                "extra_fields": {
                                  "id": "0xdb598379af06aa7c2a7e8d16bb3bf34a67f802f521fd6b58ea0ab212dfe01a6d",
                                  "size": "0"
                                }
                              }
                            ],
                            "pending_active_validators": {
                              "contents": {
                                "id": "0xc3b9a41b1a72814efb7e80690b83e51a290135baa8724d9b99c1fed36e686196",
                                "size": "0"
                              }
                            },
                            "pending_removals": [],
                            "staking_pool_mappings": {
                              "id": "0x495b48a950b6c2a504194fe7c91b74537622e5e22375ed714d05ae8d544f9dfa",
                              "size": "1"
                            },
                            "inactive_validators": {
                              "id": "0x5e9b7987ceff92070e3e3638d883e4ca97b3e3edb262258c96f018e6c2e22795",
                              "size": "0"
                            },
                            "validator_candidates": {
                              "id": "0x22cdba5f509daf502424f0d7a66425b9bbeabc686e6b2aeaa5aa4316011d3e76",
                              "size": "0"
                            },
                            "at_risk_validators": {
                              "contents": []
                            },
                            "extra_fields": {
                              "id": "0x9d7a3a63a71cd968c0edbd79f15e146fa39f2931ebc3a5a45b12039f1f5483fd",
                              "size": "0"
                            }
                          },
                          "storage_fund": {
                            "total_object_storage_rebates": {
                              "value": "0"
                            },
                            "non_refundable_balance": {
                              "value": "0"
                            }
                          },
                          "parameters": {
                            "epoch_duration_ms": "86400000",
                            "stake_subsidy_start_epoch": "0",
                            "max_validator_count": "150",
                            "min_validator_joining_stake": "30000000000000000",
                            "validator_low_stake_threshold": "20000000000000000",
                            "validator_very_low_stake_threshold": "15000000000000000",
                            "validator_low_stake_grace_period": "7",
                            "extra_fields": {
                              "id": "0x8315420196994757517a0622f591ace86895dde8d645057da3a9a2262ad9ad60",
                              "size": "0"
                            }
                          },
                          "reference_gas_price": "1000",
                          "validator_report_records": {
                            "contents": []
                          },
                          "stake_subsidy": {
                            "balance": {
                              "value": "9949700000000000000"
                            },
                            "distribution_counter": "0",
                            "current_distribution_amount": "1000000000000000",
                            "stake_subsidy_period_length": "10",
                            "stake_subsidy_decrease_rate": 1000,
                            "extra_fields": {
                              "id": "0xa042d9011db89e534b6700479269500ec754e67cb9d01d866526f62d19da44f1",
                              "size": "0"
                            }
                          },
                          "safe_mode": false,
                          "safe_mode_storage_rewards": {
                            "value": "0"
                          },
                          "safe_mode_computation_rewards": {
                            "value": "0"
                          },
                          "safe_mode_storage_rebates": "0",
                          "safe_mode_non_refundable_storage_fee": "0",
                          "epoch_start_timestamp_ms": "0",
                          "extra_fields": {
                            "id": "0x1317ce7111295e0362df770b8e541296a63a1b447546770db021f9b19ea6dd00",
                            "size": "0"
                          }
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorStateInner>"
                      },
                      "json": {
                        "id": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                        "name": "1",
                        "value": {
                          "version": "1",
                          "active_jwks": []
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                },
                {
                  "location": "0xd73b7dd2e4b15b4030f2d1af51a8e8335d37c9723565005f498df27d8a6d3a4d",
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xd73b7dd2e4b15b4030f2d1af51a8e8335d37c9723565005f498df27d8a6d3a4d",
                        "balance": {
                          "value": "30000000000000000"
                        }
                      }
                    }
                  },
                  "asMovePackage": null
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": [],
            "balanceChanges": [
              {
                "owner": {
                  "location": "0xda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd422244"
                },
                "amount": "30000000000000000",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              },
              {
                "owner": {
                  "location": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                },
                "amount": "300000000000000",
                "coinType": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                }
              }
            ],
            "objectChanges": [
              {
                "location": "0x0000000000000000000000000000000000000000000000000000000000000001",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "digest": "FvLv2TuVhx1Ga8oCLW4gZmiBnQpT7XkSdGBo753kApGD"
                }
              },
              {
                "location": "0x0000000000000000000000000000000000000000000000000000000000000002",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "digest": "CcD7UEtUeyPhcnqdxS5GFRTQ9xRsx71wZ3fRcGsaKEUp"
                }
              },
              {
                "location": "0x0000000000000000000000000000000000000000000000000000000000000003",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "digest": "4VXaAMUGRedbhHDoNifrFx2iYeC8n5qB1W6BDsUvJc3h"
                }
              },
              {
                "location": "0x0000000000000000000000000000000000000000000000000000000000000005",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "digest": "EVK8EKnUhpqHEGHYX8da98qWhQT965WLxanbCZnwaT1Y"
                }
              },
              {
                "location": "0x0000000000000000000000000000000000000000000000000000000000000006",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "digest": "D1mkJGFbzAZmXfD3ktF38Endz9LtnML94B5kuyQEhR1e"
                }
              },
              {
                "location": "0x0000000000000000000000000000000000000000000000000000000000000007",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "digest": "2aRjNBbkQWJToXLL74Wzv2GDu9sWcFPd5XXgvrgk7FAC"
                }
              },
              {
                "location": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "digest": "FX5F5Ex6asvjDd5xU8VBua8eSGp9YAh7rBse6LJsxwBa"
                }
              },
              {
                "location": "0x14498a4368db5cefb6ec2fe91cf18636c5d8fc08b91e3d1417ccb0866e8b95d4",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x14498a4368db5cefb6ec2fe91cf18636c5d8fc08b91e3d1417ccb0866e8b95d4",
                  "digest": "94HmeZ5AZqsm4X4HStQEkJqiuQWQWogMRepMzHNcfXVS"
                }
              },
              {
                "location": "0x168e8bf1317ef81399ea9fabee9e217067a257731903b45ca4915c8d049b3940",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x168e8bf1317ef81399ea9fabee9e217067a257731903b45ca4915c8d049b3940",
                  "digest": "8qJceXqDUSngLbk1rpquzALgcT4WtKfhM78LXepgZmtf"
                }
              },
              {
                "location": "0x1ca7fcc2fe39d93fd041dbcbcc30b33a366b44cab26acd52e5d99f6cf2a0a6e7",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x1ca7fcc2fe39d93fd041dbcbcc30b33a366b44cab26acd52e5d99f6cf2a0a6e7",
                  "digest": "5ZKMLAipLWCy8rkKBWVbf3NVbdEtna81wwNvt37PVdhj"
                }
              },
              {
                "location": "0x3fa556a7dadc08367a52a6eb4a3b602abbc21446c1f703d2ac46866a403d718e",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x3fa556a7dadc08367a52a6eb4a3b602abbc21446c1f703d2ac46866a403d718e",
                  "digest": "BUFgjXdbMvsknRVvLDefPKCzir7EPpkPmhinUQpD6SKy"
                }
              },
              {
                "location": "0x41a7f84bd3a02e7e5bea80580e40cec419d40ef9925a51cf0128ad84b40f8041",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x41a7f84bd3a02e7e5bea80580e40cec419d40ef9925a51cf0128ad84b40f8041",
                  "digest": "9tGfLEvq5kUWYBUaMVSH3Qu996sAv5XAPEXGUFcYecpU"
                }
              },
              {
                "location": "0x46ea41cad4b69f493f5cf7fcb41c96e63ea97c206107d9b25d29a7d28f683ca7",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x46ea41cad4b69f493f5cf7fcb41c96e63ea97c206107d9b25d29a7d28f683ca7",
                  "digest": "D5vv7Xzd6uDWFuYTSEFvNgfXrRsXSDna9v7h4BK7xQcW"
                }
              },
              {
                "location": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "digest": "BWHXYvVDVbLrXAWL91Bgid4Pu9oDyF8hZqNoFsZ6HM7w"
                }
              },
              {
                "location": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "digest": "68NRbjATuQoyL78VTc3Gd96h2xoGmevmCpoAQzM7jghG"
                }
              },
              {
                "location": "0xd73b7dd2e4b15b4030f2d1af51a8e8335d37c9723565005f498df27d8a6d3a4d",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0xd73b7dd2e4b15b4030f2d1af51a8e8335d37c9723565005f498df27d8a6d3a4d",
                  "digest": "2b3gYd9RreACiq2Cxv2LJyLS8PWHeXfDNeECYbVaf8FR"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "nPziN1DZGukFSvJ1e1AP5kJWCfjYgSTriRXB2i6BSZm"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3 'create-checkpoint'. lines 94-94:
Checkpoint created: 1

task 4 'run-graphql'. lines 96-165:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "location": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "nPziN1DZGukFSvJ1e1AP5kJWCfjYgSTriRXB2i6BSZm"
              }
            ],
            "balanceChanges": [],
            "objectChanges": [
              {
                "location": "0x0000000000000000000000000000000000000000000000000000000000000006",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "digest": "28w3Mp2x4vt94bq4TejrbLcfMsMaevDyPz6h98sgcnw4"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6 'advance-epoch'. lines 169-169:
Epoch advanced: 0

task 7 'run-graphql'. lines 171-236:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "digest": "GKoYFakg3kNVzzFVWyLUTTYw4h29b2g4Mw2qMWCRsPZe",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "location": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "value": "[ChangeEpoch(ChangeEpoch { epoch: 1, protocol_version: ProtocolVersion(32), storage_charge: 0, computation_charge: 0, storage_rebate: 0, non_refundable_storage_fee: 0, epoch_start_timestamp_ms: 85000, system_packages: [] })]"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": [
              {
                "digest": "nPziN1DZGukFSvJ1e1AP5kJWCfjYgSTriRXB2i6BSZm"
              }
            ],
            "balanceChanges": [],
            "objectChanges": [
              {
                "location": "0x0000000000000000000000000000000000000000000000000000000000000005",
                "idCreated": false,
                "idDeleted": false,
                "outputState": {
                  "location": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "digest": "J1C81xskJaop96EsuSZXSxgvodwmMnD9tdDfocXxzrFg"
                }
              },
              {
                "location": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "digest": "9QNDPxyWmCL77DX8TYzCxsZsZVnrz9URMmMjLuwnJv35"
                }
              },
              {
                "location": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                "idCreated": false,
                "idDeleted": true,
                "outputState": null
              },
              {
                "location": "0xa84a25da7fef87ac6141a4920a87564ddb5bd8964333f04e7bd49facb831ba43",
                "idCreated": true,
                "idDeleted": false,
                "outputState": {
                  "location": "0xa84a25da7fef87ac6141a4920a87564ddb5bd8964333f04e7bd49facb831ba43",
                  "digest": "BvMPQvK5F7Byp2N2nB97hSuYJ9SQz19NpiiMfBXFQFew"
                }
              }
            ],
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "GKoYFakg3kNVzzFVWyLUTTYw4h29b2g4Mw2qMWCRsPZe"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
